"""make conversation name non-unique

Revision ID: 956a307079c5
Revises: 69bba2485f87
Create Date: 2026-08-13 04:10:01.637465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '956a307079c5'
down_revision: Union[str, Sequence[str], None] = '69bba2485f87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_name'), table_name='conversations')
    op.create_index(op.f('ix_conversations_name'), 'conversations', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_name'), table_name='conversations')
    op.create_index(op.f('ix_conversations_name'), 'conversations', ['name'], unique=True)
    # ### end Alembic commands ###
